#!/usr/bin/env bash

# deterministic nc4 files

for f in energy_community_model_CO \
         energy_community_model_NA \
         energy_community_model_NC; do

  julia csv2nc4.jl ${f}
  julia csv2nc4.jl ${f} --with-network-blocks

  if [ "$f" != "energy_community_model_NA" ]; then

    julia csv2nc4.jl ${f} --with-thermal-blocks
    julia csv2nc4.jl ${f} --with-thermal-blocks --with-network-blocks

  fi

done

# stochastic nc4 files

#for f in energy_community_model_CO_sto \
#         energy_community_model_NA_sto \
#         energy_community_model_NC_sto; do
#
#  julia csv2nc4.jl ${f}
#
#  if [ "$f" != "energy_community_model_NA" ]; then
#
#    julia csv2nc4.jl ${f} --with-thermal-blocks
#
#  fi
#
#done